# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Mohammad masih/Desktop/memari project/final_project/final_project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Mohammad masih/Desktop/memari project/final_project/final_project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Mohammad masih/Desktop/memari project/final_project/final_project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/HA.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/FA2.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/FA.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/CAS.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/six_bit_adder.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/BlockY.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/BlockX.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/simple_multi.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/main.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/ROM_Module.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/RAM_Module.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/Program_Counter.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/ALU_Module.vhd}
  {C:/Users/Mohammad masih/Desktop/memari project/CA_project/State_Machine.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top State_Machine -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef State_Machine.dcp

catch { report_utilization -file State_Machine_utilization_synth.rpt -pb State_Machine_utilization_synth.pb }
